apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task4-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Davidvoodo/simple-nginx-app.git'
    targetRevision: main
    path: task4
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
