apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-task4
  annotations:
    argocd.argoproj.io/sync-wave: "1"   # sync wave שני (יבוא אחרי ה-ConfigMap)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-task4
  template:
    metadata:
      labels:
        app: nginx-task4
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: nginx-config
