apiVersion: v1
kind: Service
metadata:
  name: nginx-task4-service
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: ClusterIP
  selector:
    app: nginx-task4
  ports:
    - port: 80
      targetPort: 80
