replicaCount: 1

image:
  repository: nginx
  tag: 1.25
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: true
  name: ""

podAnnotations: {}
podLabels: {}
securityContext: {}
volumeMounts: []
volumes: []
nodeSelector: {}
affinity: {}
tolerations: []
